version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: signalbot
    volumes:
      - ./mongodb/db:/data/db
      - '.:/share'
    ports:
      - "27017:27017"
    environment:
      PUID: 1000
      PGID: 1000
#      MONGO_INITDB_ROOT_USERNAME: bb-test
#      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: signalbot
      restart: unless-stopped
